/* eslint-disable @typescript-eslint/no-explicit-any */
import { Url } from 'next/dist/shared/lib/router/router';

export interface IRepo {
  id: number;
  node_id: string | null;
  name: string | null;
  full_name: string | null;
  private: boolean | undefined;
  owner: Owner;
  html_url: Url;
  description: string | null | null;
  fork: boolean | undefined;
  url: string | null;
  forks_url: string | null;
  keys_url: string | null;
  collaborators_url: string | null;
  teams_url: string | null;
  hooks_url: string | null;
  issue_events_url: string | null;
  events_url: string | null;
  assignees_url: string | null;
  branches_url: string | null;
  tags_url: string | null;
  blobs_url: string | null;
  git_tags_url: string | null;
  git_refs_url: string | null;
  trees_url: string | null;
  statuses_url: string | null;
  languages_url: string | null;
  stargazers_url: string | null;
  contributors_url: string | null;
  subscribers_url: string | null;
  subscription_url: string | null;
  commits_url: string | null;
  git_commits_url: string | null;
  comments_url: string | null;
  issue_comment_url: string | null;
  contents_url: string | null;
  compare_url: string | null;
  merges_url: string | null;
  archive_url: string | null;
  downloads_url: string | null;
  issues_url: string | null;
  pulls_url: string | null;
  milestones_url: string | null;
  notifications_url: string | null;
  labels_url: string | null;
  releases_url: string | null;
  deployments_url: string | null;
  created_at: string | null | null;
  updated_at: string | null;
  pushed_at: string | null;
  git_url: string | null;
  ssh_url: string | null;
  clone_url: string | null;
  svn_url: string | null;
  homepage: string | null | null;
  size: number;
  stargazers_count: number;
  watchers_count: number;
  language: string | null;
  has_issues?: boolean | undefined;
  has_projects?: boolean | undefined;
  has_downloads?: boolean | undefined;
  has_wiki?: boolean | undefined;
  has_pages?: boolean | undefined;
  has_discussions?: boolean | undefined;
  forks_count: number;
  mirror_url: string | null | null;
  archived: boolean | undefined;
  disabled: boolean | undefined;
  open_issues_count: number;
  license: any;
  allow_forking?: boolean | undefined;
  is_template?: boolean | undefined;
  web_commit_signoff_required?: boolean | undefined;
  topics?: string[] | undefined;
  visibility?: string | undefined;
  forks: number;
  open_issues: number;
  watchers: number;
  default_branch: string | null;
  permissions?: any;
}

type Owner = {
  login: string | null;
  id: number;
  node_id: string | null;
  avatar_url: string | null;
  gravatar_id: string | null;
  url: string | null;
  html_url: string | null;
  followers_url: string | null;
  following_url: string | null;
  gists_url: string | null;
  starred_url: string | null;
  subscriptions_url: string | null;
  organizations_url: string | null;
  repos_url: string | null;
  events_url: string | null;
  received_events_url: string | null;
  type: string | null;
  site_admin: boolean;
};
